/*
@title: Alien Invaders
@author: Aditi Ranjan
*/

const player = "p";
const bullet = "b";
const alien = "a";

setLegend(
  [player, bitmap`
................
................
.......000......
.......0.0......
......0..0......
......0...0.0...
....0003.30.0...
....0.0...000...
....0.05550.....
......0...0.....
.....0....0.....
.....0...0......
......000.......
......0.0.......
.....00.00......
................`],
  [bullet, bitmap`
................
................
.......3........
.......3........
.......3........
.......3........
.......3........
.......3........
.......3........
.......3........
.......3........
.......3........
.......3........
................
................
................`],
  [alien, bitmap`
................
................
.....111111.....
....11222211....
...1122222211...
...1122222211...
...1122222211...
...1122222211...
....11222211....
.....111111.....
......1111......
.....112211.....
....11222211....
....11222211....
................
................`]
);

setSolids([player, alien]);

let level = 0;
const levels = [
  map`
................
................
................
................
................
................
................
.a.a.a.a.a.a.a.a
................
.p..............`
];

setMap(levels[level]);

setPushables({
  [player]: []
});

onInput("a", () => {
  getFirst(player).x -= 1;
});
onInput("d", () => {
  getFirst(player).x += 1;
});

onInput("s", () => {
  let p = getFirst(player);
  let b = addSprite(p.x, p.y - 1, bullet);
  b.velocity = { x: 0, y: -1 };
});

afterInput(() => {
  getAll(bullet).forEach(b => {
    if (b.y <= 0) {
      b.remove();
    } else {
      let hitAlien = getAll(alien).find(a => a.x === b.x && a.y === b.y);
      if (hitAlien) {
        hitAlien.remove();
        b.remove();
      }
    }
  });

  getAll(alien).forEach(a => {
    if (a.y >= getFirst(player).y) {
      addText("Game Over", { x: 8, y: 4, color: color`3` });
    } else {
      a.y += 1;
    }
  });

  if (getAll(alien).length === 0) {
    addText("You Win!", { x: 8, y: 4, color: color`2` });
  }
});
